# Site
title:              Elizabeth Smedley, PhD
bio:                'Postdoc @ Dartmouth College'
description:        ""
reading_time:       false
words_per_minute:   200
logo:               'assets/img/profpic1.jpg'
background:         'assets/img/dartmouth_campus.jpg'
tiled_bg:           false   # Set this true if you want to tile your background image, otherwise it will be covered
locale:             en_US
url:                https://ebsmedley.github.io

# Jekyll
permalink:          /:title/
markdown:           kramdown
highlighter:        rouge
kramdown:
  auto_ids:         true
  footnote_nr:      1
  entity_output:    as_char
  toc_levels:       1..6
  enable_coderay:   false
mathjax:            true
sass:
  sass_dir:         _sass
  style:            compressed

# Comments
disqus_shortname:   ebsmedley

# Social
# if you don't have any of social below, comment the line.
#google:
  #plus:            #username
  #analytics:
  #verify:
  #ad-client:
  #ad-slot:
#bing-verify:
email:		    Elizabeth.B.Smedley.gr@dartmouth.edu
twitter:            ebsmed
#facebook:           #ebsmedley
github-url:         ebsmedley
#stackoverflow:     #123456/username   from a "http://stackoverflow.com/users/123456/username" link
linkedin:           elizabeth-smedley-5364238b
#xing:              username
#Instagram:          #ebsmedley
#lastfm:            username
#tumblr:            username
#medium:            '@username'
#pinterest:         username
#foursquare:        username
#steam:              username
#dribbble:          username
#youtube:           username
#youtube-channel:   channel
#soundcloud:        username
#weibo:             username
#flickr:            username
#codepen:           username
#keybase:           username
#xmpp:              username@server.com
#hackernews:        username
scholar:	    citations?user=z5MHV2gAAAAJ&hl=en

# Gems
gems:
  - jekyll-mentions
  - jekyll-feed
  - jekyll-sitemap
  - jekyll-gist

jekyll-mentions:
    base_url: https://github.com

# Exclude list
exclude: [README.md, Gemfile, Gemfile.lock, node_modules, gulpfile.js, package.json, _site, src, vendor, CNAME, LICENSE, Rakefile]
